---
"qa":
  repoconfig:
    consumers:
      - name: consumer2
        data:
          regopackage: dev
          protocol: web
          url: http
        rego:
          regopackage: dev
          protocol: git
          url: http

